name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.target}})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
        - os: windows-latest
          target: x86_64-pc-windows-msvc
        - os: macos-latest
          target: x86_64-apple-darwin
        - os: ubuntu-latest
          target: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose --release

      - name: Pack
        shell: bash
        run: |
          mkdir bin
          if [ "$OS" = "Windows_NT" ]; then
            cp target/release/recast.exe bin
            7z a recast-${{ matrix.target }}.zip bin tools
          else
            cp target/release/recast bin
            zip -r recast-${{ matrix.target }}.zip bin tools
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: draft
          files: recast-${{ matrix.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
