name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.target}})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        target:
        - x86_64-pc-windows-msvc
        - x86_64-apple-darwin
        - aarch64-apple-darwin
        - x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Compile binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target "${{ matrix.target }}" --release
